"$schema"       = 'https://starship.rs/config-schema.json'

add_newline     = true
command_timeout = 200
scan_timeout = 2000
# format = "[$directory$git_branch$git_status]($style)$character"

[character]
error_symbol   = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[directory]
# truncation_length   = 2
# truncation_symbol   = "…/"
# Vrepo_root_style    = "bold cyan"
# repo_root_format    = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
truncate_to_repo      = false
truncation_length     = 0
truncation_symbol     = ""

[git_branch]
# format   = "[$branch]($style) "
# style    = "italic cyan"
disabled   = false

[git_status]
disabled   = true
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

